### ISSUE TITLE
Spelling: Componenets

### ISSUE THREAD

**Issue by jamesrudolph** [Lazik10/TwilightImperiumUltimate#71]
Low Priority

![Screenshot_20241029-145745_Chrome.jpg](https://github.com/user-attachments/assets/7323b794-9bb8-40b3-9ca7-ea8188b940ec)

Given that almost all occurrences of this word is spelled "wrong" I have to assume it's just a translation issue.

English spelling is "Components"

**Comment by Lazik10** [comment]
Hi, thank you for reporting this, 

someone else has already mentioned this in the reddit post, but I didn't have time to create an issue here.

For some reason when I type this word fast I always write it this incorrect way, even though I know that it is spelled components.
I fixed it already. The label itself, as well as occurrences in the code. It will be pushed live in few days. I want to update also system tiles from Ascendant Sun (Eronous). They are creating a white gap due to bad cropping when downloading map image and it doesn't look good. And with other few small corrections / fixes.
